-- Role: mtcg_user
-- DROP ROLE mtcg_user;

CREATE ROLE mtcg_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:2mWw/tWdq41KZqYAmsJiiQ==$ACb6OKNA9VwKVAp8AX4fF6ylav299UcB3cWWEwjp2Xc=:jFSjrOOWnic9o1bA2hWnrrslIZg3eNZWmBrC5kD72VU=';
