using System;
using System.Collections.Generic;
using System.Net;

namespace RestWebServer
{
    /// <summary>
    /// Represents the response generated by the request handler.
    /// This will be sent back to the client.
    /// </summary>
    public class RestResponse
    {
        /// <summary>
        /// The HTTP status code.
        /// </summary>
        public HttpStatusCode StatusCode { get; }

        /// <summary>
        /// Additional custom HTTP headers.
        /// </summary>
        public IDictionary<string, string> Headers { get; }

        /// <summary>
        /// The content of the body.
        /// </summary>
        public string Payload { get; }

        public RestResponse(HttpStatusCode statusCode)
        {
            StatusCode = statusCode;
            Headers = new Dictionary<string, string>();
            Payload = string.Empty;
        }

        public RestResponse(HttpStatusCode statusCode, string payload)
        {
            StatusCode = statusCode;
            Headers = new Dictionary<string, string>();
            Payload = payload;
        }

        public RestResponse(HttpStatusCode statusCode, IDictionary<string, string> headers)
        {
            StatusCode = statusCode;
            Headers = headers;
            Payload = string.Empty;
        }

        public RestResponse(HttpStatusCode statusCode, IDictionary<string, string> headers, string payload)
        {
            StatusCode = statusCode;
            Headers = headers;
            Payload = payload;
        }
    }
}
